In [2]:
import numpy as np 
import math


#Shubham Singh
#21250025
#Assignment-3
#Task-3

# Input Parameters
arr = np.array([])
n = int(input("Enter number of links in the manipulator: "))
for i in range(1):
    Ques = input("Joint is Revolute or Prismatic? \n Type 0 for revolute\n Type 1 for prismatic\n")

for i in range(0, n):
    print('Enter theta',i)
    para = int(input())
    arr = np.append(arr, para)
for i in range(0, n):
    print('Enter alpha',i)
    para1 = int(input())
    arr = np.append(arr, para1)  
for i in range(0, n):
    print('Enter a',i)
    para2 = int(input())
    arr = np.append(arr, para2)
for i in range(0, n):
    print('Enter d',i)
    para3 = int(input())
    arr = np.append(arr, para3)
print(arr)


if n == 3:   
    d_h_table = np.array([[np.deg2rad(arr[0]),   np.deg2rad(arr[3]), arr[6],   arr[9]],
                      [np.deg2rad(arr[1]),   np.deg2rad(arr[4]), arr[7],   arr[10]],
                      [np.deg2rad(arr[2]),   np.deg2rad(arr[5]), arr[8],   arr[11]],])

    i = 0                
    homgen_0_1 = np.array([[np.cos(d_h_table[i,0]), -np.sin(d_h_table[i,0]) * np.cos(d_h_table[i,1]), np.sin(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.cos(d_h_table[i,0])],
                        [np.sin(d_h_table[i,0]), np.cos(d_h_table[i,0]) * np.cos(d_h_table[i,1]), -np.cos(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.sin(d_h_table[i,0])],
                        [0, np.sin(d_h_table[i,1]), np.cos(d_h_table[i,1]), d_h_table[i,3]],
                        [0, 0, 0, 1]])  
    
    i = 1
    homgen_1_2 = np.array([[np.cos(d_h_table[i,0]), -np.sin(d_h_table[i,0]) * np.cos(d_h_table[i,1]), np.sin(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.cos(d_h_table[i,0])],
                        [np.sin(d_h_table[i,0]), np.cos(d_h_table[i,0]) * np.cos(d_h_table[i,1]), -np.cos(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.sin(d_h_table[i,0])],
                        [0, np.sin(d_h_table[i,1]), np.cos(d_h_table[i,1]), d_h_table[i,3]],
                        [0, 0, 0, 1]])  
    
    i = 2
    homgen_2_3 = np.array([[np.cos(d_h_table[i,0]), -np.sin(d_h_table[i,0]) * np.cos(d_h_table[i,1]), np.sin(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.cos(d_h_table[i,0])],
                        [np.sin(d_h_table[i,0]), np.cos(d_h_table[i,0]) * np.cos(d_h_table[i,1]), -np.cos(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.sin(d_h_table[i,0])],
                        [0, np.sin(d_h_table[i,1]), np.cos(d_h_table[i,1]), d_h_table[i,3]],
                        [0, 0, 0, 1]])  
    homgen_0_3 = homgen_0_1 @ homgen_1_2 @ homgen_2_3  

    print("Homogeneous Matrix Frame 0 to Frame 3 is :\n")
    print(homgen_0_3)

    #Position in X direction
    px = homgen_0_3[0,3]
    print("Position of End effector in X direction is:\n", px)

    #Position in y direction
    py = homgen_0_3[1,3]
    print("Position of End effector in y direction is:\n", py)

    pz = homgen_0_3[2,3]
    print("Position of End effector in z direction is:\n", py)

    answer = int(input("Is the manipulator SCARA ? \n Enter 0 for Yes/n Enter 1 for No \n"))
    
    if answer == 0:
        J_ = np.array([[-arr[6]*np.sin(arr[0])-arr[7]*np.sin(arr[0]+arr[1]), -arr[7]*np.sin(arr[0]), 0],            #Calculating Jacobian Matrix
                            [arr[6]*np.cos(arr[0])+ arr[7]*np.cos(arr[0]), arr[7]*np.cos(arr[0]), 0],
                            [0, 0, 0],
                            [0, 0, 0],
                            [0, 0, 0],
                            [1, 1, -1]]) 
        print("Manipulator Jacobian Matrix is", J_)
    
    elif answer == 1:
        J__ = np.array([[(-arr[9]*np.sin(arr[0])+arr[10]*np.sin(arr[0]+arr[1])+arr[11]*np.sin(arr[0]+arr[1]+arr[2])), (-arr[10]*np.sin(arr[0]+arr[1])+arr[11]*np.sin(arr[0]+arr[1]+arr[2])), (-arr[11]*np.sin(arr[0]+arr[1]+arr[2]))],               #Calculating Jacobian Matrix
                                [(arr[9]*np.cos(arr[0])+ arr[10]*np.cos(arr[0]+arr[1])), (arr[11]*np.cos(arr[0]+arr[1]+arr[2]), arr[10]*np.cos(arr[0]+arr[1])+arr[11]*np.cos(arr[0]+arr[1]+arr[2])), (arr[11]*np.cos(arr[0]+arr[1]+arr[2]))],
                                [0, 0, 0],
                                [0, 0, 0],
                                [0, 0, 0],
                                [1, 1, 1]]) 
        
        print('The manipulator is Stanford\n',J__)

    vc3 = np.array([[-arr[6]*np.sin(arr[0]), -arr[7]*np.sin(arr[1]), arr[8]*np.sin(arr[2])/2],
                [arr[6]*np.cos(arr[0]), arr[7]*np.cos(arr[1]), arr[8]*np.cos(arr[2])/2],
                    [0, 0, 0]]) 
    print("End effector velocity matrix is:\n",vc3)


elif n == 2:
    d_h_table = np.array([[np.deg2rad(arr[0]),   np.deg2rad(arr[2]), arr[4],   arr[6]],
                      [np.deg2rad(arr[1]),   np.deg2rad(arr[3]), arr[5],   arr[7]]])
                     
    # Homogeneous transformation matrix 
    i = 0
    homgen_0_1 = np.array([[np.cos(d_h_table[i,0]), -np.sin(d_h_table[i,0]) * np.cos(d_h_table[i,1]), np.sin(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.cos(d_h_table[i,0])],
                        [np.sin(d_h_table[i,0]), np.cos(d_h_table[i,0]) * np.cos(d_h_table[i,1]), -np.cos(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.sin(d_h_table[i,0])],
                        [0, np.sin(d_h_table[i,1]), np.cos(d_h_table[i,1]), d_h_table[i,3]],
                        [0, 0, 0, 1]])  
    i = 1
    homgen_1_2 = np.array([[np.cos(d_h_table[i,0]), -np.sin(d_h_table[i,0]) * np.cos(d_h_table[i,1]), np.sin(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.cos(d_h_table[i,0])],
                        [np.sin(d_h_table[i,0]), np.cos(d_h_table[i,0]) * np.cos(d_h_table[i,1]), -np.cos(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.sin(d_h_table[i,0])],
                        [0, np.sin(d_h_table[i,1]), np.cos(d_h_table[i,1]), d_h_table[i,3]],
                        [0, 0, 0, 1]])  
    homgen_0_2 = homgen_0_1 @ homgen_1_2 
    
    print("Homogeneous Matrix Frame 0 to Frame 2 is :\n")
    print(homgen_0_2)

    #Position in X direction
    px = homgen_0_2[0,3]
    print("Position of End effector in X direction is:\n", px)
    
    #Position in y direction
    py = homgen_0_2[1,3]
    print("Position of End effector in y direction is:\n", py)

    py = homgen_0_2[2,3]
    print("Position of End effector in z direction is:\n", py)

    J_ = np.array([[-arr[4]*np.sin(arr[0])-arr[5]*np.sin(arr[0]+arr[1]), -arr[5]*np.sin(arr[0]+arr[1])],
        [-arr[4]*np.cos(arr[0])-arr[5]*np.cos(arr[0]+arr[1]), -arr[5]*np.cos(arr[0]+arr[1])],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 1]])
    print('The manipulator jacobin matrix is\n',J_)

    vc2 = np.array([[-arr[4]*np.sin(arr[0]), -arr[5]*np.sin(arr[1])/2],
                [arr[4]*np.cos(arr[0]), arr[5]*np.cos(arr[1])/2],
                    [0, 0]])
    print("End effector velocity matrix is:\n",vc2)

elif n == 6:   
    d_h_table = np.array([[np.deg2rad(arr[0]),   np.deg2rad(arr[6]), arr[12],   arr[18]],
                      [np.deg2rad(arr[1]),   np.deg2rad(arr[7]), arr[13],   arr[19]],
                      [np.deg2rad(arr[2]),   np.deg2rad(arr[8]), arr[14],   arr[20]],
                      [np.deg2rad(arr[3]),   np.deg2rad(arr[9]), arr[15],   arr[21]],
                      [np.deg2rad(arr[4]),   np.deg2rad(arr[10]), arr[16],   arr[22]],
                      [np.deg2rad(arr[5]),   np.deg2rad(arr[11]), arr[17],   arr[23]],])
    i = 0                
    homgen_0_1 = np.array([[np.cos(d_h_table[i,0]), -np.sin(d_h_table[i,0]) * np.cos(d_h_table[i,1]), np.sin(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.cos(d_h_table[i,0])],
                        [np.sin(d_h_table[i,0]), np.cos(d_h_table[i,0]) * np.cos(d_h_table[i,1]), -np.cos(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.sin(d_h_table[i,0])],
                        [0, np.sin(d_h_table[i,1]), np.cos(d_h_table[i,1]), d_h_table[i,3]],
                        [0, 0, 0, 1]])  
    
    i = 1
    homgen_1_2 = np.array([[np.cos(d_h_table[i,0]), -np.sin(d_h_table[i,0]) * np.cos(d_h_table[i,1]), np.sin(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.cos(d_h_table[i,0])],
                        [np.sin(d_h_table[i,0]), np.cos(d_h_table[i,0]) * np.cos(d_h_table[i,1]), -np.cos(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.sin(d_h_table[i,0])],
                        [0, np.sin(d_h_table[i,1]), np.cos(d_h_table[i,1]), d_h_table[i,3]],
                        [0, 0, 0, 1]])  
    
    i = 2
    homgen_2_3 = np.array([[np.cos(d_h_table[i,0]), -np.sin(d_h_table[i,0]) * np.cos(d_h_table[i,1]), np.sin(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.cos(d_h_table[i,0])],
                        [np.sin(d_h_table[i,0]), np.cos(d_h_table[i,0]) * np.cos(d_h_table[i,1]), -np.cos(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.sin(d_h_table[i,0])],
                        [0, np.sin(d_h_table[i,1]), np.cos(d_h_table[i,1]), d_h_table[i,3]],
                        [0, 0, 0, 1]])  
    i = 3
    homgen_3_4 = np.array([[np.cos(d_h_table[i,0]), -np.sin(d_h_table[i,0]) * np.cos(d_h_table[i,1]), np.sin(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.cos(d_h_table[i,0])],
                        [np.sin(d_h_table[i,0]), np.cos(d_h_table[i,0]) * np.cos(d_h_table[i,1]), -np.cos(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.sin(d_h_table[i,0])],
                        [0, np.sin(d_h_table[i,1]), np.cos(d_h_table[i,1]), d_h_table[i,3]],
                        [0, 0, 0, 1]]) 
    i = 4
    homgen_4_5 = np.array([[np.cos(d_h_table[i,0]), -np.sin(d_h_table[i,0]) * np.cos(d_h_table[i,1]), np.sin(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.cos(d_h_table[i,0])],
                        [np.sin(d_h_table[i,0]), np.cos(d_h_table[i,0]) * np.cos(d_h_table[i,1]), -np.cos(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.sin(d_h_table[i,0])],
                        [0, np.sin(d_h_table[i,1]), np.cos(d_h_table[i,1]), d_h_table[i,3]],
                        [0, 0, 0, 1]]) 
    i = 5
    homgen_5_6 = np.array([[np.cos(d_h_table[i,0]), -np.sin(d_h_table[i,0]) * np.cos(d_h_table[i,1]), np.sin(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.cos(d_h_table[i,0])],
                        [np.sin(d_h_table[i,0]), np.cos(d_h_table[i,0]) * np.cos(d_h_table[i,1]), -np.cos(d_h_table[i,0]) * np.sin(d_h_table[i,1]), d_h_table[i,2] * np.sin(d_h_table[i,0])],
                        [0, np.sin(d_h_table[i,1]), np.cos(d_h_table[i,1]), d_h_table[i,3]],
                        [0, 0, 0, 1]]) 
    homgen_6_7 = homgen_0_1 @ homgen_1_2 @ homgen_2_3  @ homgen_3_4 @ homgen_4_5 @ homgen_5_6
    print("Homogeneous Matrix Frame 0 to Frame 6 is :\n")
    print(homgen_6_7)

    #Position in X direction
    px = homgen_6_7[0,3]
    print("Position of End effector in X direction is:\n", px)

    #Position in y direction
    py = homgen_6_7[1,3]
    print("Position of End effector in y direction is:\n", py)

    pz = homgen_6_7[2,3]
    print("Position of End effector in z direction is:\n", pz)

    J_ = np.array([[(-np.cos(arr[0])*arr[19]-np.sin(arr[0])*np.sin(arr[1])*arr[20]) , np.cos(arr[0])*np.cos(arr[1])*arr[20] , np.cos(arr[0])*np.sin(arr[1]), 0, 0, 0 ],
    [(-np.sin(arr[0])*arr[19]+np.cos(arr[0])*np.sin(arr[1])*arr[20]), np.sin(arr[0])*np.cos(arr[1])*arr[20] , np.sin(arr[0])*np.sin(arr[1]), 0, 0, 0 ],
    [0, np.sin(arr[1])*arr[20], np.sin(arr[1]), 0, 0, 0],
    [0, -np.sin(arr[0]), 0, np.cos(arr[0])*np.sin(arr[1])*arr[20], -np.sin(arr[0])*np.cos(arr[1])*np.sin(arr[3])+np.cos(arr[0])*np.cos(arr[3]), 0],
    [0,np.cos(arr[0]), 0 , np.sin(arr[0])*np.sin(arr[1])*arr[20], -np.sin(arr[0])*np.cos(arr[1])*np.sin(arr[3])+np.cos(arr[0])*np.cos(arr[3]), 0],
    [1, 0, 0, np.cos(arr[1]), np.sin(arr[1])*np.sin(arr[3]), 0]])

    print("Manipulator Jacobian Matrix is",J_)

    



  
 

 
 
 



Enter number of links in the manipulator: 3
Joint is Revolute or Prismatic? 
 Type 0 for revolute
 Type 1 for prismatic
0
Enter theta 0
45
Enter theta 1
45
Enter theta 2
45
Enter alpha 0
0
Enter alpha 1
0
Enter alpha 2
0
Enter a 0
1
Enter a 1
2
Enter a 2
3
Enter d 0
0
Enter d 1
0
Enter d 2
0
[45. 45. 45.  0.  0.  0.  1.  2.  3.  0.  0.  0.]
Homogeneous Matrix Frame 0 to Frame 3 is :

[[-0.70710678 -0.70710678  0.         -1.41421356]
 [ 0.70710678 -0.70710678  0.          4.82842712]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
Position of End effector in X direction is:
 -1.414213562373094
Position of End effector in y direction is:
 4.828427124746191
Position of End effector in z direction is:
 4.828427124746191
Is the manipulator SCARA ? 
 Enter 0 for Yes/n Enter 1 for No 
0
Manipulator Jacobian Matrix is [[-2.63889685 -1.70180705  0.        ]
 [ 1.57596597  1.05064398  0.        ]
 [ 0.          0.          0.        ]
 [ 0.

Task_11

In [4]:
import sympy as sp
import numpy as np
from sympy import *
from sympy import diff, sin, cos

#Shubham Singh
#21250025
#Task_11

arr = []
arr1 = []
print("Enter Number of Symbols to be defined:")
dimen_1 = int(input())

for i in range(dimen_1):
    print("Enter Symbol",i+1)
    arr1.append(input())
    arr1[i]=sp.symbols(arr1[i])

n = int(input("Enter Number of links"))    
row_1, column_1 = (n, n)
d_q= [[0 for i in range(column_1)] for j in range(row_1)]
v_q=[]
P= n**2
row_3, column_3 = (P, n)
cqqd= [[0 for i in range(column_3)] for j in range(row_3)]
row_4, column_4 = (n,1)
v_qd= [[0 for i in range(column_4)] for j in range(row_4)]
for i in range(n):            
    for j in range(n):
        print("enter the elements of D_q",i,j,".")
        d_q[i][j]=input()
for i in range(n):
    print("Enter V_Q",i,j,".")
    v_q=input()    
   
for i in range(n):
    for j in range(n):
        n=0
        for arr in range(n):
            cqqd[m][n]=0.5*(sp.diff(d_q[arr][j],arr1[i])+sp.diff(d_q[arr][i],arr1[j])-sp.diff(d_q[i][j],arr1[arr]))
            n=n+1
        m=m+1
        print(cqqd)
        for m in range(n):
          v_qd[m]=sp.diff(v_q,arr1[m])  
          print(v_qd)

    
    
            
            





















Enter Number of Symbols to be defined:
2
Enter Symbol 1
m1
Enter Symbol 2
m2
Enter Number of links2
enter the elements of D_q 0 0 .
m1
enter the elements of D_q 0 1 .
m2
enter the elements of D_q 1 0 .
m1
enter the elements of D_q 1 1 .
m2
Enter V_Q 0 1 .
m1
Enter V_Q 1 1 .
m2
[[0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0]]
