Task_1

In [1]:
import numpy as np
import math 

#Shubham Singh
#21250025
#Assignment-4
#Task-1
 
# Define the desired position of the end effector

Px = float(input("End effector position in X direction:"))
Py = float(input("End effector position in y direction:"))
Pz = float(input("End effector position in z direction:"))

d1_ = int(input("Enter the value of d1:"))
theta1 = math.atan2(Px, Py)

r = math.sqrt(Px*Px + Py*Py)
s = Pz- d1_
theta2 = math.atan2(r, s)

d3 = math.sqrt((Px*Px +Py*Py)+((Pz - d1_)*(Pz - d1_)))
angle1 = math.degrees(theta1)
angle2 = math.degrees(theta2)

theta12 = math.pi + math.atan2(Px, Py)
theta22 = math.pi - math.atan2(r, s)

angle3 = math.degrees(theta12)
angle4 = math.degrees(theta22)

if d1_ == 0:
    print("Value of Theta_1 in degrees ", angle1, "\n")
    print("Value of Theta_2 in degrees",angle2, "\n")

#If there is an offset d1 not equal to zero, then the wrist centre cannot intersect the Zo axis.
#In this case there will be in general two solutions for theta1 & theta2.
elif d1_ >= 1:

    print("Value of Theta_1 in degrees:", angle1 ,"\n")
    print("Value of Theta_2 in degrees:",angle2, "\n")
    print("Value of Second solution of Theta_1 in degrees:", angle3, "\n")
    print("Value of Second solution of Theta_2 in degrees:",angle4, "\n")
print("The value of linear distance d3:", d3)

End effector position in X direction:2
End effector position in y direction:4
End effector position in z direction:5
Enter the value of d1:1
Value of Theta_1 in degrees: 26.56505117707799 

Value of Theta_2 in degrees: 48.18968510422141 

Value of Second solution of Theta_1 in degrees: 206.565051177078 

Value of Second solution of Theta_2 in degrees: 131.8103148957786 

The value of linear distance d3: 6.0


Task_2

In [7]:
#Shubham Singh
#21250025
#Assignment-4
#Task-2

import numpy as np
import math 
Px = float(input("End effector position in X direction:"))
Py = float(input("End effector position in y direction:"))
Pz = float(input("End effector position in z direction:"))
a1 = 4
a2 = 5
d2 = 1
d4 = 2


r_square = ((Px*Px + Py*Py - a1*a1 - a2*a2)/(2*a1*a2))
l = math.sqrt(1-r_square)
theta_2 = math.atan2(l, math.sqrt(r_square))
theta_1 = math.atan2(Px, Py)-math.atan2((a1 + a2*np.cos(theta_2)), (a2*np.sin(theta_2)))

rot_mat_ = np.array([[-np.sin(theta_2), 0.0, np.cos(theta_2)],
                        [np.cos(theta_2), 0.0, np.sin(theta_2)],
                        [0.0, 1.0, 0.0]])
theta_4 = theta_1 + theta_2 - math.atan2(rot_mat_[0,1], rot_mat_[0,0])
d3 = d2 + d4

angle1 = math.degrees(theta_1)
angle2 = math.degrees(theta_2)
angle4 = math.degrees(theta_4)

print("Value of Theta_1 in degrees:", angle1 ,"\n")
print("Value of Theta_2 in degrees:",angle2, "\n")
print("Value of Second solution of Theta_2 in degrees:",angle4, "\n")
print("The value of linear distance d3:", d3)

End effector position in X direction:5
End effector position in y direction:4
End effector position in z direction:1
Value of Theta_1 in degrees: 12.68038349181982 

Value of Theta_2 in degrees: 90.0 

Value of Second solution of Theta_2 in degrees: -77.31961650818018 

The value of linear distance d3: 3


Task_3

In [9]:
#Shubham Singh
#21250025
#Assignment-4
#Task-3


import numpy as np
import math

n=int(input("Number of links: "))
dh=[0]*n
R_or_P=[0]*n

print("Link,  theta_i,  d_i,  a_i ,  alpha_i")
for i in range(n):
    dh[i]=[eval(j) for j in input(str(i+1)+" "*6).split()]
lst=[int(i) for i in input("Prismatic joints if any (leave empty if none): ").split()]
for i in lst:
    R_or_P[i-1]=1

A=[0]*n
for i in range(n):
    theta, d, a, alpha = dh[i]
    A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                   [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                   [0, np.sin(alpha), np.cos(alpha), d],
                   [0, 0, 0, 1]])
ans=np.identity(4)
Z=[0]*(n+1)
Z[0]=np.array([[0],
               [0],
               [1]])

O=[0]*(n+1)
O[0]=np.array([0, 0, 0])

for i in range(n):
    ans=ans@A[i]
    Z[i+1]=ans[0:3, 0:3]@Z[0]
    O[i+1]=ans[0:3,3].T
J=[0]*n
for i in range(n):
    if R_or_P[i]==1:
        J[i]=np.concatenate((Z[i],np.array([[0,0,0]]).T),axis=0)
    else:
        cross=np.cross(Z[i].T,(O[n]-O[i]).T)
        J[i]=np.concatenate((cross.T,Z[i]),axis=0)

final_J=J[0]
for i in range(1,n):
    final_J=np.concatenate((final_J,J[i]),axis=1)

print("Jacobian Matrix is:", final_J)

dots=input("Enter x_dot: ("+str(n)+" values) ")
print()
x_dots=[int(i) for i in dots.split()]          

print("Joint Velocities:")
if n == 6:
    ki = np.linalg.inv(final_J)

    q_dot = ki@x_dots
    print(q_dot)

else:
    print(" Jacobian is not invertible")


Number of links: 6
Link,  theta_i,  d_i,  a_i ,  alpha_i
1      45 0 0 90
2      45 0 2 0
3      90 0 0 -90
4      -90 0 2 45
5      45 0 0 0 
6      90 0 0 2
Prismatic joints if any (leave empty if none): 
Jacobian Matrix is: [[-0.6485164   0.28073977  0.77416012 -0.43705108  0.          0.        ]
 [ 2.51400791 -1.14240457  0.55297269 -1.86494634  0.          0.        ]
 [ 0.          1.6739985   0.73472629 -0.57529253 -0.         -0.        ]
 [ 0.          0.76070491  0.76070491 -0.72187126 -0.19327069 -0.19327069]
 [ 0.         -0.46963611 -0.46963611  0.35281736  0.97878742  0.97878742]
 [ 1.         -0.44807362 -0.44807362 -0.59533335 -0.06798248 -0.06798248]]
Enter x_dot: (6 values) 2 4 6 8 2 1

Joint Velocities:
[ 3.95459680e+00  1.69370631e+00  7.80080474e+00  4.46158778e+00
  1.64754248e+17 -1.64754248e+17]


Task_6

In [13]:
#Shubham Singh
#21250025
#Assignment-4
#Task_6

import numpy as np
import math 
 
# Define the desired position of the end effector
Px = float(input("End effector position in X direction:"))
Py = float(input("End effector position in y direction:"))


theta_2 = np.arctan2(Py,Px)
theta_2_ = math.degrees(theta_2)
print(f'\nTheta_2 in degrees = {theta_2_}\n')
 
rot_mat_0_6 = np.array([[-1.0, 0.0, 0.0],
                        [0.0, -1.0, 0.0],
                        [0.0, 0.0, 1.0]])
 
rot_mat_0_3 = np.array([[-np.sin(theta_2), 0.0, np.cos(theta_2)],
                        [np.cos(theta_2), 0.0, np.sin(theta_2)],
                        [0.0, 1.0, 0.0]])
 
inv_rot_mat_0_3 = np.linalg.inv(rot_mat_0_3)
 
# Calculate the 3x3 rotation matrix of frame 6 relative to frame 3
rot_mat_3_6 = inv_rot_mat_0_3 @ rot_mat_0_6
theta_5 = np.arccos(rot_mat_3_6[2, 2])
theta_5_ = math.degrees(theta_5)
print(f'\nValue of Theta_5 in degrees = {theta_5_}')
 
theta_6 = np.arccos(rot_mat_3_6[2, 0] / -np.sin(theta_5))
theta_6_ = math.degrees(theta_6)
print(f'\n Value of Theta_6 in degrees = {theta_6_}')
 
theta_4 = np.arccos(rot_mat_3_6[1,2] / np.sin(theta_5))
theta_4_ = math.degrees(theta_4)
print(f'\n Value of Theta_4 in degrees = {theta_4_}')


End effector position in X direction:4
End effector position in y direction::6

Theta_2 in degrees = 56.309932474020215


Value of Theta_5 in degrees = 90.0

 Value of Theta_6 in degrees = 56.30993247402021

 Value of Theta_4 in degrees = 0.0


Compute_Task-7

In [24]:

# Input DH Parameters of 3D Printer from the PDF attached with the folder as "Task_7"
# DH paramters being used to compute the end effector position, Jacobian & Velocities of the 3D printer

#Assume d1=1, d2=1 , d3 =1 for computing the values

import numpy as np
import scipy
         
def my_function(j):

 A[0][0]=np.cos(theta[j]);
 A[0][1]=-np.sin(theta[j])*np.cos(alpha[j]);
 A[0][2]=np.sin(theta[j])*np.sin(alpha[j]);
 A[0][3]=np.cos(theta[j])*r[j];
 A[1][0]=np.sin(theta[j]);
 A[1][1]=np.cos(theta[j])*np.cos(alpha[j]);
 A[1][2]=-np.cos(theta[j])*np.sin(alpha[j]);
 A[1][3]=np.sin(theta[j])*r[j];
 A[2][0]=0;
 A[2][1]=np.sin(alpha[j]);
 A[2][2]=np.cos(alpha[j]);
 A[2][3]=depth[j];
 A[3][0]=0;
 A[3][1]=0;
 A[3][2]=0;
 A[3][3]=1;
 return A
def my_funch(c,v): 
    for i in range(c,v):
        if i!=c:
            B=B@np.array(my_function(i))   
        else:
            B=np.array(my_function(i));    
    return B;
def JacobianCol(i,l):
    
        z=[[0],[0],[0]];
        if joint[i]==0:
            Zo=ZIM1(i);
            K=np.transpose(z);
            K1=np.transpose(Zo);
            RAF=np.concatenate((K1,K),axis=1);
            RAF1=np.transpose(RAF);
            return(RAF1)
        else:
            omain=Ocal(l);
            ocha=Ocal(i);
            Ofin=omain-ocha;
            zag=ZIM1(i);
            zag2=np.transpose(zag);
            Ofim=np.transpose(Ofin);                                             
            PAF=np.cross(zag2,Ofim);
            PAF2=np.transpose(PAF);
            PAF1=np.concatenate((PAF2,zag),axis=0);
            return(PAF1);
def ZIM1(k):
 zat=[[0],[0],[1]];
 
 if k==0:
     return zat;
 else:
     RA=my_funch(0,k);
     RAn1=np.delete(RA,[3],0);
     RAn2=np.delete(RAn1,[3],1);
     
     zat=[[0],[0],[1]];
     KA=np.matmul(RAn2,zat);
     return KA
     
def Ocal(k):
    rat=[[0],[0],[0]];
    if k==0:
        return rat;
    else:
        RA=my_funch(0,k);
        RAn1=np.delete(RA,[3],0);
        RAn2=np.delete(RAn1,[0,1,2],1);     
        return RAn2;
        
print("enter the no. of links");
l=int(input());
joint= np.array([1]*l);
depth=[0]*l;
r=[0]*l;
theta=[0]*l;
alpha=[0]*l;

A = [[0 for x in range(4)] for y in range(4)] 

print("self mode or auto press 1 for auto 0 for self");
s=int(input());
if s==0:
    for i in range(l):
        print("please  enter 1 for revolute and 0 for prismatic");
        joint[i]=int(input());
else:
    joint=[1]*l;
    
for n in range(l):
    print("enter the depth for",n+1," link");
    depth[n]=float(input());
    print("enter the aaa for",n+1," link");
    r[n]=float(input()); #r=a
    print("enter the theta for",n+1," link in degrees");
    theta[n]=(np.pi/180)*float(input());
    print("enter the alpha for",n+1,"link in degrees");
    alpha[n]=(np.pi/180)*float(input());        
    
for i in range(l):
    if i==0:
        J1=JacobianCol(i,l);
    else:
        J1=np.concatenate((J1,JacobianCol(i,l)),axis=1);

print("1JACOBIAN")
print(np.round_(J1,decimals=2))

vel=[0]*l;
for n in range(l):
    print("enter the endeff velocity vector for x y z as follows wrt last link");
    vel[n]=float(input());000
P2=np.matmul(J1,np.transpose(vel));
print("END EFFECTOR VELOCITY VECTOR")
print(np.round_(P2,decimals=2))      
H=np.round_(my_funch(0,l))
P=np.delete(H,[3],0);
P3=np.delete(P,[0,1,2],1);
print("END EFFECTOR POSITION VECTOR")
print(np.round_(abs(P3),decimals=2))
print(np.round_(H,decimals=2))
N=np.round_(my_funch(0,l))
RAn4=np.delete(N,[3],0);
RAn5=np.delete(RAn4,[3],1);
print("Final R");
print(np.round_(RAn5,decimals=2));

enter the no. of links
3
self mode or auto press 1 for auto 0 for self
0
please  enter 1 for revolute and 0 for prismatic
0
please  enter 1 for revolute and 0 for prismatic
0
please  enter 1 for revolute and 0 for prismatic
0
enter the depth for 1  link
1
enter the aaa for 1  link
0
enter the theta for 1  link in degrees
0
enter the alpha for 1 link in degrees
-90
enter the depth for 2  link
1
enter the aaa for 2  link
0
enter the theta for 2  link in degrees
90
enter the alpha for 2 link in degrees
90
enter the depth for 3  link
1
enter the aaa for 3  link
0
enter the theta for 3  link in degrees
-90
enter the alpha for 3 link in degrees
0
1JACOBIAN
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
enter the endeff velocity vector for x y z as follows wrt last link
1
enter the endeff velocity vector for x y z as follows wrt last link
4
enter the endeff velocity vector for x y z as follows wrt last link
5
END EFFECTOR VELOCITY VECTOR
[5. 4. 1. 0. 0. 0.]
END EFFEC